version: '3.7'
services:
    php:
        container_name: php
        build:
            dockerfile: php.Dockerfile
            context: ./docker/php
        environment:
            PHP_IDE_CONFIG: "serverName=Pay"
            XDEBUG_CONFIG: remote_host=192.168.2.167
        volumes:
          - ./:/var/www/html
          - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
